# Corrected 10-class configuration for COCO classification
image_size: 224
class_ids: [1, 3, 18, 17, 2, 6, 8, 9, 62, 15]
class_names: [person, car, dog, cat, bicycle, bus, truck, boat, chair, bench]
compress_options: [16, 32, 64]
use_patch: false
train_ratio: 0.85
split_seed: 42

